<h1> Embeddings v1 <h1>


In [ ]:
import numpy as np

# Given sentences
sentences = ["the mouse ran up the clock", "the mouse ran down"]

# Step 1: Create the vocabulary
# Split sentences into words and flatten the list
words = [word for sentence in sentences for word in sentence.split()]
vocab = sorted(set(words))

print(vocab)

['clock', 'down', 'mouse', 'ran', 'the', 'up']


In [ ]:
# Step 2: Create word-to-index mapping
word_to_index = {word: i for i, word in enumerate(vocab)}

print(word_to_index)

{'clock': 0, 'down': 1, 'mouse': 2, 'ran': 3, 'the': 4, 'up': 5}


In [ ]:
# Parameters for embeddings
vocab_size = len(vocab)  # Size of the vocabulary
embedding_dim = 64  # Dimensionality of the embeddings

# Step 3: Generate random embeddings
np.random.seed(42)  # For reproducibility
embeddings = np.random.rand(vocab_size, embedding_dim)
print(embeddings[:5, :4]) # just for print example purpose taking :5, :4

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.28093451 0.54269608 0.14092422 0.80219698]
 [0.00695213 0.5107473  0.417411   0.22210781]
 [0.90041806 0.63310146 0.33902979 0.34920957]
 [0.93615477 0.6960298  0.57006117 0.09717649]]


In [ ]:
# Step 4: Lookup function
def get_embedding(word):
    # Check if the word is in the vocabulary
    if word in word_to_index:
        word_idx = word_to_index[word]
        return embeddings[word_idx]
    else:
        return None

In [ ]:
# Example usage
word = "mouse"
embedding_vector = get_embedding(word)
print(f"Embedding for '{word}':\n{embedding_vector}")


<h1> Embeddings with Keras v2 <h1>


In [ ]:
# Using Keras


import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Given sentences
sentences = ["the mouse ran up the clock", "the mouse ran down"]

# Step 1: Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

# Vocabulary size (adding 1 because of reserved 0 index)
vocab_size = len(tokenizer.word_index) + 1

# Step 2: Define the embedding layer within a model
embedding_dim = 64

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=1, name="embedding_layer"),
])

# Dummy forward pass to initialize embeddings
# Note: This step is not necessary for embedding lookup but is shown here for completeness.
# Normally, you would train your model here.

# Step 3: Function to get embeddings
def get_embedding(word):
    try:
        # Convert the word to its index in the vocabulary
        word_index = tokenizer.word_index[word]
        # Get embeddings from the embedding layer
        embeddings = model.get_layer('embedding_layer').get_weights()[0]
        return embeddings[word_index]
    except KeyError:
        return None

# Example usage
word = "mouse"
embedding_vector = get_embedding(word)
print(f"Embedding for '{word}':\n{embedding_vector}")


In [ ]:
%%capture
!pip3 install -q sentence_transformers

<h1> Using Pre-trained Embeddings Models <h1>


In [ ]:
from sentence_transformers import SentenceTransformer

sentence = ["What you do, the way you think, makes you beautiful."]

# Initialize a SentenceTransformer model named 'paraphrase-MiniLM-L6-v2'
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Encode the list of sentences using the SentenceTransformer model
embedded_data = model.encode(sentence)

# Print the embedded data
print(embedded_data)


[[ 4.72032875e-01  2.93646276e-01  5.29063165e-01  2.74275839e-01
  -1.64800823e-01 -3.82772833e-01  5.94015300e-01 -2.04411730e-01
  -1.85515806e-01  1.05437256e-01  1.03318788e-01 -2.14283660e-01
   1.14359692e-01 -1.46845371e-01  2.45816499e-01  2.35646799e-01
   4.20987815e-01  3.02350372e-01 -7.56477594e-01  2.22802252e-01
  -1.17485054e-01 -3.27175319e-01  6.71170428e-02 -7.38552585e-02
   1.27316499e-02 -4.40868065e-02 -2.68764095e-03  1.75503775e-01
  -3.88823718e-01 -2.61820138e-01 -4.22599399e-03 -1.81634530e-01
  -4.18887347e-01  1.66062340e-01 -3.23095709e-01  3.36429685e-01
  -5.53131938e-01 -1.17904872e-01  2.38818735e-01  9.96864140e-02
   3.30198258e-02 -1.30512208e-01 -1.29074007e-01  3.59890796e-02
   1.10384151e-01 -3.21421564e-01  5.90231836e-01  2.19548300e-01
   1.65504992e-01 -1.07095309e-01 -7.57104218e-01 -4.42518264e-01
  -2.92941928e-01 -4.41340864e-01 -1.44943550e-01  7.40716159e-01
  -1.33454964e-01 -1.04245886e-01  1.99248403e-01 -2.42412314e-01
   2.30108